//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBROnline.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBR_MST_FGLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EBR_MST_FGLocation()
        {
            this.EBR_Dashboard = new HashSet<EBR_Dashboard>();
            this.EBR_Dashboard1 = new HashSet<EBR_Dashboard>();
            this.EBR_Dashboard2 = new HashSet<EBR_Dashboard>();
            this.EBR_Dashboard3 = new HashSet<EBR_Dashboard>();
            this.EBR_Dashboard4 = new HashSet<EBR_Dashboard>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBR_Dashboard> EBR_Dashboard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBR_Dashboard> EBR_Dashboard1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBR_Dashboard> EBR_Dashboard2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBR_Dashboard> EBR_Dashboard3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBR_Dashboard> EBR_Dashboard4 { get; set; }
    }
}
