//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBROnline.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBR_Dashboard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EBR_Dashboard()
        {
            this.EBR_SubDashboard = new HashSet<EBR_SubDashboard>();
        }
    
        public int Id { get; set; }
        public string Device { get; set; }
        public string Rev { get; set; }
        public string FABDieRevision { get; set; }
        public string PMPN { get; set; }
        public string AMPN { get; set; }
        public string TMPN { get; set; }
        public string FMPN { get; set; }
        public string CPN_SAP_Material { get; set; }
        public Nullable<int> PackageId { get; set; }
        public string PackageSize { get; set; }
        public string Leads { get; set; }
        public string Speed { get; set; }
        public string EABI_EBR_Revision { get; set; }
        public Nullable<int> WaferSizeId { get; set; }
        public string CurrentWaferThichness { get; set; }
        public string InternalDevice { get; set; }
        public Nullable<int> FabCodeId { get; set; }
        public string Power_Voltage { get; set; }
        public Nullable<int> DieBlankId { get; set; }
        public Nullable<int> AssemblyLocationnId { get; set; }
        public Nullable<int> FGLocationId { get; set; }
        public string AssemblyFlow { get; set; }
        public Nullable<int> PackageTypeId { get; set; }
        public Nullable<int> TopSideMarkingId { get; set; }
        public string MRL { get; set; }
        public string NameOfMarkingFile { get; set; }
        public Nullable<bool> RequiresSepecialMark { get; set; }
        public Nullable<bool> RequiresAssEngrInput { get; set; }
        public Nullable<int> MarkingCodeId { get; set; }
        public string Pin1Marking { get; set; }
        public string TopLine { get; set; }
        public string C2ndLine { get; set; }
        public string C3rdLine { get; set; }
        public string C4thLine { get; set; }
        public string C5thLine { get; set; }
        public string C6thLine { get; set; }
        public Nullable<int> ShipFinishedProductToId { get; set; }
        public string AttentionFinished { get; set; }
        public Nullable<int> ShipRejectedPartToId { get; set; }
        public string AttentionRejected { get; set; }
        public Nullable<int> ReturnWaferToId { get; set; }
        public Nullable<int> VendorContactId { get; set; }
        public Nullable<int> VendorCodeId { get; set; }
        public Nullable<int> PurposeOfBuildId { get; set; }
        public Nullable<int> LotOwnerId { get; set; }
        public Nullable<int> RequestCycleTimeId { get; set; }
        public Nullable<int> PKGProcessId { get; set; }
        public Nullable<int> QualityLevelId { get; set; }
        public Nullable<int> RevenueLocationId { get; set; }
        public Nullable<bool> BondDiagramAttached { get; set; }
        public Nullable<bool> ScrapExcessDie_Wafer { get; set; }
        public Nullable<bool> UV_Erase { get; set; }
        public Nullable<bool> DieCoat { get; set; }
        public Nullable<int> WireMaterialId { get; set; }
        public Nullable<int> ProcessLTSID { get; set; }
        public Nullable<bool> ForecastMaterial { get; set; }
        public string BondDiagram { get; set; }
        public string BondDiagramRev { get; set; }
        public string EngineerTeam { get; set; }
        public Nullable<int> TestLocationId { get; set; }
        public Nullable<int> ProbeStatusId { get; set; }
        public Nullable<int> PackageTestTypeId { get; set; }
        public string TestProgram { get; set; }
        public Nullable<bool> TestProgamAvailable { get; set; }
        public string CommentAvaliable { get; set; }
        public string Test_Sepecial_Instruction { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<int> EmailAddressId { get; set; }
        public string Phone { get; set; }
        public Nullable<int> RequesterLocationId { get; set; }
        public string BusinessUnit { get; set; }
        public string ApprovingManager { get; set; }
        public Nullable<int> ManagerEmailId { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<System.DateTime> RequestedShipDate { get; set; }
        public Nullable<bool> RequiresTestPgmApproval { get; set; }
        public bool IsDeleted { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public byte StatusType { get; set; }
        public Nullable<bool> NPILot { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
    
        public virtual EBR_MST_AssemblyLocation EBR_MST_AssemblyLocation { get; set; }
        public virtual EBR_MST_BuildReason EBR_MST_BuildReason { get; set; }
        public virtual EBR_MST_DieBank EBR_MST_DieBank { get; set; }
        public virtual EBR_MST_EmailAddress EBR_MST_EmailAddress { get; set; }
        public virtual EBR_MST_EmailAddress EBR_MST_EmailAddress1 { get; set; }
        public virtual EBR_MST_FabCode EBR_MST_FabCode { get; set; }
        public virtual EBR_MST_FGLocation EBR_MST_FGLocation { get; set; }
        public virtual EBR_MST_FGLocation EBR_MST_FGLocation1 { get; set; }
        public virtual EBR_MST_FGLocation EBR_MST_FGLocation2 { get; set; }
        public virtual EBR_MST_FGLocation EBR_MST_FGLocation3 { get; set; }
        public virtual EBR_MST_FGLocation EBR_MST_FGLocation4 { get; set; }
        public virtual EBR_MST_MarkingInstruction EBR_MST_MarkingInstruction { get; set; }
        public virtual EBR_MST_MarkingSL EBR_MST_MarkingSL { get; set; }
        public virtual EBR_MST_Owner EBR_MST_Owner { get; set; }
        public virtual EBR_MST_Package EBR_MST_Package { get; set; }
        public virtual EBR_MST_PackageTestType EBR_MST_PackageTestType { get; set; }
        public virtual EBR_MST_PackingType EBR_MST_PackingType { get; set; }
        public virtual EBR_MST_PKGProcessType EBR_MST_PKGProcessType { get; set; }
        public virtual EBR_MST_PriorityOfAssemblyBuild EBR_MST_PriorityOfAssemblyBuild { get; set; }
        public virtual EBR_MST_ProbeStatus EBR_MST_ProbeStatus { get; set; }
        public virtual EBR_MST_ProcessLTS EBR_MST_ProcessLTS { get; set; }
        public virtual EBR_MST_QualityLevel EBR_MST_QualityLevel { get; set; }
        public virtual EBR_MST_RequesterLocation EBR_MST_RequesterLocation { get; set; }
        public virtual EBR_MST_RevenueLocation EBR_MST_RevenueLocation { get; set; }
        public virtual EBR_MST_VendorCode EBR_MST_VendorCode { get; set; }
        public virtual EBR_MST_VendorContact EBR_MST_VendorContact { get; set; }
        public virtual EBR_MST_WaferSize EBR_MST_WaferSize { get; set; }
        public virtual EBR_MST_WireMaterial EBR_MST_WireMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBR_SubDashboard> EBR_SubDashboard { get; set; }
    }
}
