//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBROnline.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EBROnlineEntities : DbContext
    {
        public EBROnlineEntities()
            : base("name=EBROnlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EBR_Dashboard> EBR_Dashboard { get; set; }
        public virtual DbSet<EBR_MST_AssemblyLocation> EBR_MST_AssemblyLocation { get; set; }
        public virtual DbSet<EBR_MST_BuildReason> EBR_MST_BuildReason { get; set; }
        public virtual DbSet<EBR_MST_DieBank> EBR_MST_DieBank { get; set; }
        public virtual DbSet<EBR_MST_EmailAddress> EBR_MST_EmailAddress { get; set; }
        public virtual DbSet<EBR_MST_FabCode> EBR_MST_FabCode { get; set; }
        public virtual DbSet<EBR_MST_FGLocation> EBR_MST_FGLocation { get; set; }
        public virtual DbSet<EBR_MST_MarkingInstruction> EBR_MST_MarkingInstruction { get; set; }
        public virtual DbSet<EBR_MST_MarkingSL> EBR_MST_MarkingSL { get; set; }
        public virtual DbSet<EBR_MST_Owner> EBR_MST_Owner { get; set; }
        public virtual DbSet<EBR_MST_Package> EBR_MST_Package { get; set; }
        public virtual DbSet<EBR_MST_PackageTestType> EBR_MST_PackageTestType { get; set; }
        public virtual DbSet<EBR_MST_PackingType> EBR_MST_PackingType { get; set; }
        public virtual DbSet<EBR_MST_PKGProcessType> EBR_MST_PKGProcessType { get; set; }
        public virtual DbSet<EBR_MST_PriorityOfAssemblyBuild> EBR_MST_PriorityOfAssemblyBuild { get; set; }
        public virtual DbSet<EBR_MST_ProbeStatus> EBR_MST_ProbeStatus { get; set; }
        public virtual DbSet<EBR_MST_ProcessLTS> EBR_MST_ProcessLTS { get; set; }
        public virtual DbSet<EBR_MST_QualityLevel> EBR_MST_QualityLevel { get; set; }
        public virtual DbSet<EBR_MST_RequesterLocation> EBR_MST_RequesterLocation { get; set; }
        public virtual DbSet<EBR_MST_RevenueLocation> EBR_MST_RevenueLocation { get; set; }
        public virtual DbSet<EBR_MST_VendorCode> EBR_MST_VendorCode { get; set; }
        public virtual DbSet<EBR_MST_VendorContact> EBR_MST_VendorContact { get; set; }
        public virtual DbSet<EBR_MST_WaferSize> EBR_MST_WaferSize { get; set; }
        public virtual DbSet<EBR_MST_WireMaterial> EBR_MST_WireMaterial { get; set; }
        public virtual DbSet<EBR_SYS_Roles> EBR_SYS_Roles { get; set; }
        public virtual DbSet<EBR_SYS_Users> EBR_SYS_Users { get; set; }
        public virtual DbSet<EBR_SubDashboard> EBR_SubDashboard { get; set; }
    }
}
